import { Metadata } from "next";

export const metadata: Metadata = {
  //title: "Next.js-15",
  title: {
    default: "Next.js-15 | Default MD", //fallback value.
    template: "%s | Default MD", //consistent prefixes or suffixes to our title. The property applies to the CHILD routes
    //absolute: "", // not here, in the children routes
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "lightgray",
            color: "black",
            padding: "5px",
          }}>
          <p>My Header</p>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: "lightblue",
            color: "black",
            padding: "5px",
          }}>
          <p>My Footer</p>
        </footer>
      </body>
    </html>
  );
}
